[package]

name = "nickel_redis"
version = "0.0.0"
authors = [
    "bguiz",
    "Matthew Bentley <matthew@bentley.link>"
]

[dependencies]
redis = "*"
r2d2 = "*"
plugin = "*"
typemap = "*"
openssl = "*"
nickel = "*"

[dependencies.r2d2_redis]
git = "https://github.com/nevdelap/r2d2-redis.git"
