[package]

name = "nickel_redis"
version = "0.0.0"
authors = [
    "bguiz",
    "Matthew Bentley <matthew@bentley.link>"
]

[dependencies]
redis = "*"
r2d2 = "*"
r2d2_redis = "*"
plugin = "*"
typemap = "*"
openssl = "*"
nickel = "*"
